
name: Check TF with Checkov
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  checkov:
    name: Checkov - ${{ matrix.project.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - name: account-resources
            path: aws/tools/account-resources
          - name: ci-vpc
            path: aws/tools/ci-vpc
          - name: ci-eks-cluster
            path: aws/tools/ci-eks-cluster
          - name: ci-kube-argo
            path: aws/tools/ci-kube-argo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # https://github.com/actions/setup-python
      - name: Set up Python 3.9
        uses: actions/setup-python@v6.1.0
        with:
          python-version: 3.9

      # https://github.com/bridgecrewio/checkov-action
      - name: Test account-resources with Checkov
        id: account-resources
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ matrix.project.path }}
          framework: terraform
          skip_check: CKV2_AWS_5,CKV2_AWS_11,CKV2_AWS_12,CKV_AWS_23,CKV_AWS_37,CKV_AWS_38,CKV_AWS_39,CKV_AWS_58,CKV_AWS_100,CKV_AWS_111,CKV_AWS_356,CKV_AWS_382
          output: sarif
          output-file-path: results/${{ matrix.project.name }}.sarif

      - name: Upload Checkov SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-${{ matrix.project.name }}
          path: results/${{ matrix.project.name }}.sarif

#      # https://github.com/bridgecrewio/checkov-action
#      - name: Test account-resources with Checkov
#        id: account-resources
#        uses: bridgecrewio/checkov-action@v12
#        with:
#          directory: aws/tools/account-resources
#          framework: terraform
##          config_file: ../../checkov.yml

#      - name: Test ci-vpc with Checkov
#        id: ci-vpc
#        uses: bridgecrewio/checkov-action@v12
#        with:
#          directory: aws/tools/ci-vpc
#          framework: terraform
#          skip_check: CKV2_AWS_11,CKV2_AWS_12,CKV_AWS_130
#
#      - name: Test ci-eks-cluster with Checkov
#        id: ci-eks-cluster
#        uses: bridgecrewio/checkov-action@v12
#        with:
#          directory: aws/tools/ci-eks-cluster
#          framework: terraform
#          skip_check: CKV2_AWS_5,CKV2_AWS_11,CKV2_AWS_12,CKV_AWS_23,CKV_AWS_37,CKV_AWS_38,CKV_AWS_39,CKV_AWS_58,CKV_AWS_100,CKV_AWS_111,CKV_AWS_356,CKV_AWS_382
#      #          config_file: checkov.yml
#
#      - name: Test ci-kube-argo with Checkov
#        id: ci-kube-argo
#        uses: bridgecrewio/checkov-action@v12
#        with:
#          directory: aws/tools/ci-kube-argo
#          framework: terraform
##          config_file: ../../checkov.yml

