
name: Check TF with Checkov
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  checkov:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # https://github.com/actions/setup-python
      - name: Set up Python 3.9
        uses: actions/setup-python@v6.1.0
        with:
          python-version: 3.9

      # https://github.com/bridgecrewio/checkov-action
      - name: Test account-resources with Checkov
        id: account-resources
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: aws/tools/account-resources
          framework: terraform
          config_file: ../../checkov.yml

#      - name: Test ci-vpc with Checkov
#        id: ci-vpc
#        uses: bridgecrewio/checkov-action@v12
#        with:
#          directory: aws/tools/ci-vpc
#          framework: terraform

      - name: Test ci-eks-cluster with Checkov
        id: ci-eks-cluster
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: aws/tools/ci-eks-cluster
          framework: terraform
          config_file: ../../checkov.yml

      - name: Test ci-kube-argo with Checkov
        id: ci-kube-argo
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: aws/tools/ci-kube-argo
          framework: terraform
          config_file: ../../checkov.yml